# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [82]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense, LeakyReLU
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

from sklearn.decomposition import PCA

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [3]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv(
    Path('./Resources/applicants_data.csv')
)

# Review the DataFrame
applicant_data_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [5]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns=['EIN','NAME'])

# Review the DataFrame
applicant_data_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [8]:
# Create a list of categorical variables 
categorical_variables = list(applicant_data_df.dtypes[applicant_data_df.dtypes=="object"].index)

# Display the categorical variables list
categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [15]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [16]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])
encoded_data

array([[1., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [17]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(
    encoded_data,
    columns = enc.get_feature_names(categorical_variables)
)

# Review the DataFrame
encoded_df.head()

c:\Users\lmros\anaconda3\envs\dev\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [27]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df = pd.concat([applicant_data_df.drop(columns=categorical_variables),encoded_df],axis=1)

# Review the Dataframe
encoded_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,1,36500179,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [29]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df["IS_SUCCESSFUL"]

# Display a sample of y
y.head(10)

0    1
1    1
2    0
3    1
4    1
5    1
6    1
7    1
8    1
9    0
Name: IS_SUCCESSFUL, dtype: int64

In [32]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(columns=["IS_SUCCESSFUL"])

# Review the features DataFrame
X.head()

,STATUS,ASK_AMT,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 6: Split the features and target sets into training and testing datasets.

In [33]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [34]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [35]:
# Define the the number of inputs (features) to the model
number_input_features = 116

# Review the number of features
number_input_features

116

In [36]:
# Define the number of neurons in the output layer
number_output_neurons =1

In [37]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 = int(number_input_features / 2)

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

58

In [38]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  int(hidden_nodes_layer1/2)

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

29

In [41]:
# Create the Sequential model instance
nn = Sequential()

In [42]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1,input_dim=number_input_features,activation="relu"))

In [44]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2,activation="relu"))

In [45]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=1,activation="sigmoid"))

In [47]:
# Display the Sequential model summary
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 58)                6786

 dense_1 (Dense)             (None, 29)                1711

 dense_2 (Dense)             (None, 1)                 30

=================================================================
Total params: 8,527
Trainable params: 8,527
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [49]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])

In [50]:
# Fit the model using 50 epochs and the training data
nn.fit(X_train_scaled,y_train,epochs=50)

Epoch 1/50
804/804 [==============================] - 7s 6ms/step - loss: 0.5744 - accuracy: 0.7223
Epoch 2/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5550 - accuracy: 0.7278
Epoch 3/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5505 - accuracy: 0.7301
Epoch 4/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5486 - accuracy: 0.7317
Epoch 5/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5465 - accuracy: 0.7327
Epoch 6/50
804/804 [==============================] - 5s 7ms/step - loss: 0.5454 - accuracy: 0.7319
Epoch 7/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5453 - accuracy: 0.7320
Epoch 8/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5439 - accuracy: 0.7341
Epoch 9/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5433 - accuracy: 0.7332
Epoch 10/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5425 - accuracy: 0.7342
Epoch 11/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5418 - accuracy: 0.7347
Epoch 12/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5412 - accuracy: 0.7359
Epoch 13/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5405 - accuracy: 0.7351
Epoch 14/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5402 - accuracy: 0.7355
Epoch 15/50
804/804 [==============================] - 4s 6ms/step - loss: 0.5397 - accuracy: 0.7354
Epoch 16/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5396 - accuracy: 0.7366
Epoch 17/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5389 - accuracy: 0.7372
Epoch 18/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5388 - accuracy: 0.7369
Epoch 19/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5385 - accuracy: 0.7365
Epoch 20/50
804/804 [==============================] - 4s 6ms/step - loss: 0.5381 - accuracy: 0.7372
Epoch 21/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5380 - accuracy: 0.7371
Epoch 22/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5375 - accuracy: 0.7377
Epoch 23/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5378 - accuracy: 0.7367
Epoch 24/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5367 - accuracy: 0.7381
Epoch 25/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5370 - accuracy: 0.7378
Epoch 26/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5365 - accuracy: 0.7386
Epoch 27/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5361 - accuracy: 0.7384
Epoch 28/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5360 - accuracy: 0.7390
Epoch 29/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5357 - accuracy: 0.7386
Epoch 30/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5356 - accuracy: 0.7381
Epoch 31/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5355 - accuracy: 0.7388
Epoch 32/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5349 - accuracy: 0.7385
Epoch 33/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5352 - accuracy: 0.7377
Epoch 34/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5351 - accuracy: 0.7395
Epoch 35/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5346 - accuracy: 0.7394
Epoch 36/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5344 - accuracy: 0.7393
Epoch 37/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5343 - accuracy: 0.7385
Epoch 38/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5340 - accuracy: 0.7394
Epoch 39/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5339 - accuracy: 0.7405
Epoch 40/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5339 - accuracy: 0.7404
Epoch 41/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5337 - accuracy: 0.7391
Epoch 42/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5336 - accuracy: 0.7389
Epoch 43/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5335 - accuracy: 0.7398
Epoch 44/50
804/804 [==============================] - 6s 7ms/step - loss: 0.5331 - accuracy: 0.7393
Epoch 45/50
804/804 [==============================] - 6s 7ms/step - loss: 0.5333 - accuracy: 0.7395
Epoch 46/50
804/804 [==============================] - 6s 7ms/step - loss: 0.5330 - accuracy: 0.7403
Epoch 47/50
804/804 [==============================] - 6s 7ms/step - loss: 0.5328 - accuracy: 0.7400
Epoch 48/50
804/804 [==============================] - 6s 7ms/step - loss: 0.5327 - accuracy: 0.7409
Epoch 49/50
804/804 [==============================] - 5s 7ms/step - loss: 0.5326 - accuracy: 0.7405
Epoch 50/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5322 - accuracy: 0.7404

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [51]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=1)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 [==============================] - 2s 5ms/step - loss: 0.5532 - accuracy: 0.7296
Loss: 0.5531627535820007, Accuracy: 0.7295626997947693

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [52]:
# Set the model's file path
file_path = Path('Resources/AlphabetSoup.h5')

# Export your model to a HDF5 file
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [53]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [69]:
#import seaborn as sns
X_train.dtypes
#ax = sns.heatmap(X_train.corr())

#no consistent correlation, then applying PCA for dimension reduction


n_reduced_inputs = 58
pca = PCA(n_components=n_reduced_inputs)

pca.fit(X_train_scaled)

X_train_pca = pca.transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)

In [66]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [65]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = 32

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

32

In [67]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [70]:
# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1_A1,input_dim=n_reduced_inputs,activation="relu"))


# Output layer
nn_A1.add(Dense(units=number_output_neurons_A1,activation="sigmoid"))


# Check the structure of the model
nn_A1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 32)                1888

 dense_4 (Dense)             (None, 1)                 33

=================================================================
Total params: 1,921
Trainable params: 1,921
Non-trainable params: 0
_________________________________________________________________

In [71]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])

In [72]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_pca,y_train,epochs=50)

Epoch 1/50
804/804 [==============================] - 5s 4ms/step - loss: 0.5952 - accuracy: 0.7088
Epoch 2/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5632 - accuracy: 0.7255
Epoch 3/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5591 - accuracy: 0.7291
Epoch 4/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5573 - accuracy: 0.7296
Epoch 5/50
804/804 [==============================] - 4s 4ms/step - loss: 0.5563 - accuracy: 0.7285
Epoch 6/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5531 - accuracy: 0.7303
Epoch 7/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5525 - accuracy: 0.7306
Epoch 8/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5514 - accuracy: 0.7321
Epoch 9/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5517 - accuracy: 0.7303
Epoch 10/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5506 - accuracy: 0.7299
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5498 - accuracy: 0.7306
Epoch 12/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5495 - accuracy: 0.7310
Epoch 13/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5488 - accuracy: 0.7325
Epoch 14/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5489 - accuracy: 0.7306
Epoch 15/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5485 - accuracy: 0.7307
Epoch 16/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5480 - accuracy: 0.7314
Epoch 17/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5472 - accuracy: 0.7331
Epoch 18/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5477 - accuracy: 0.7320
Epoch 19/50
804/804 [==============================] - 4s 4ms/step - loss: 0.5474 - accuracy: 0.7322
Epoch 20/50
804/804 [==============================] - 4s 4ms/step - loss: 0.5464 - accuracy: 0.7324
Epoch 21/50
804/804 [==============================] - 4s 4ms/step - loss: 0.5473 - accuracy: 0.7321
Epoch 22/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5467 - accuracy: 0.7326
Epoch 23/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5468 - accuracy: 0.7320
Epoch 24/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5460 - accuracy: 0.7329
Epoch 25/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5457 - accuracy: 0.7326
Epoch 26/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5455 - accuracy: 0.7326
Epoch 27/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5456 - accuracy: 0.7338
Epoch 28/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5453 - accuracy: 0.7334
Epoch 29/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5459 - accuracy: 0.7316
Epoch 30/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5453 - accuracy: 0.7324
Epoch 31/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5453 - accuracy: 0.7347
Epoch 32/50
804/804 [==============================] - 4s 4ms/step - loss: 0.5447 - accuracy: 0.7334
Epoch 33/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5451 - accuracy: 0.7337
Epoch 34/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5451 - accuracy: 0.7344
Epoch 35/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5449 - accuracy: 0.7338
Epoch 36/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5448 - accuracy: 0.7329
Epoch 37/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5445 - accuracy: 0.7341
Epoch 38/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5437 - accuracy: 0.7345
Epoch 39/50
804/804 [==============================] - 4s 4ms/step - loss: 0.5441 - accuracy: 0.7338
Epoch 40/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5443 - accuracy: 0.7345
Epoch 41/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5438 - accuracy: 0.7345
Epoch 42/50
804/804 [==============================] - 4s 4ms/step - loss: 0.5443 - accuracy: 0.7344
Epoch 43/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5435 - accuracy: 0.7350
Epoch 44/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5440 - accuracy: 0.7339
Epoch 45/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5440 - accuracy: 0.7345
Epoch 46/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5433 - accuracy: 0.7331
Epoch 47/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5437 - accuracy: 0.7348
Epoch 48/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5434 - accuracy: 0.7352
Epoch 49/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5433 - accuracy: 0.7346
Epoch 50/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5435 - accuracy: 0.7339

#### Alternative Model 2

In [73]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [75]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [76]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = 64

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

64

In [77]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer2_A2 = 32

# Review the number of hidden nodes in the first layer
hidden_nodes_layer2_A2

32

In [97]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [98]:
# First hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer1_A2,input_dim=n_reduced_inputs,activation=LeakyReLU(alpha=0.02)))

#Second hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer2_A2,activation=LeakyReLU(alpha=0.01)))

# Output layer
nn_A2.add(Dense(units=number_output_neurons_A2,activation="tanh"))

# Check the structure of the model
nn_A2.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_17 (Dense)            (None, 64)                3776

 dense_18 (Dense)            (None, 32)                2080

 dense_19 (Dense)            (None, 1)                 33

=================================================================
Total params: 5,889
Trainable params: 5,889
Non-trainable params: 0
_________________________________________________________________

In [99]:
# Compile the model
nn_A2.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])

In [96]:
# Fit the model
nn_A2.fit(X_train_pca,y_train,epochs=60)

Epoch 1/60
804/804 [==============================] - 3s 3ms/step - loss: 0.8549 - accuracy: 0.6476
Epoch 2/60
804/804 [==============================] - 4s 5ms/step - loss: 0.8548 - accuracy: 0.6562
Epoch 3/60
804/804 [==============================] - 4s 5ms/step - loss: 0.8546 - accuracy: 0.6577
Epoch 4/60
804/804 [==============================] - 4s 5ms/step - loss: 0.8541 - accuracy: 0.6549
Epoch 5/60
804/804 [==============================] - 3s 4ms/step - loss: 0.8538 - accuracy: 0.6557
Epoch 6/60
804/804 [==============================] - 3s 4ms/step - loss: 0.8541 - accuracy: 0.6554
Epoch 7/60
804/804 [==============================] - 4s 5ms/step - loss: 0.8541 - accuracy: 0.6573
Epoch 8/60
804/804 [==============================] - 4s 5ms/step - loss: 0.8533 - accuracy: 0.6573
Epoch 9/60
804/804 [==============================] - 4s 5ms/step - loss: 0.8532 - accuracy: 0.6594
Epoch 10/60
804/804 [==============================] - 4s 5ms/step - loss: 0.8532 - accuracy: 0.6580
Epoch 11/60
804/804 [==============================] - 4s 5ms/step - loss: 0.8531 - accuracy: 0.6564
Epoch 12/60
804/804 [==============================] - 4s 5ms/step - loss: 0.8528 - accuracy: 0.6579
Epoch 13/60
804/804 [==============================] - 4s 5ms/step - loss: 0.8529 - accuracy: 0.6561
Epoch 14/60
804/804 [==============================] - 4s 5ms/step - loss: 0.8522 - accuracy: 0.6570
Epoch 15/60
804/804 [==============================] - 3s 4ms/step - loss: 0.8525 - accuracy: 0.6594
Epoch 16/60
804/804 [==============================] - 4s 5ms/step - loss: 0.8522 - accuracy: 0.6569
Epoch 17/60
804/804 [==============================] - 4s 5ms/step - loss: 0.8526 - accuracy: 0.6588
Epoch 18/60
804/804 [==============================] - 3s 4ms/step - loss: 0.8524 - accuracy: 0.6579
Epoch 19/60
804/804 [==============================] - 3s 4ms/step - loss: 0.8524 - accuracy: 0.6574
Epoch 20/60
804/804 [==============================] - 4s 5ms/step - loss: 0.8519 - accuracy: 0.6580
Epoch 21/60
804/804 [==============================] - 4s 5ms/step - loss: 0.8515 - accuracy: 0.6562
Epoch 22/60
804/804 [==============================] - 4s 5ms/step - loss: 0.8521 - accuracy: 0.6581
Epoch 23/60
804/804 [==============================] - 3s 4ms/step - loss: 0.8514 - accuracy: 0.6563
Epoch 24/60
804/804 [==============================] - 4s 5ms/step - loss: 0.8515 - accuracy: 0.6567
Epoch 25/60
804/804 [==============================] - 4s 5ms/step - loss: 0.8520 - accuracy: 0.6593
Epoch 26/60
804/804 [==============================] - 4s 5ms/step - loss: 0.8508 - accuracy: 0.6590
Epoch 27/60
804/804 [==============================] - 3s 4ms/step - loss: 0.8511 - accuracy: 0.6573
Epoch 28/60
804/804 [==============================] - 4s 4ms/step - loss: 0.8510 - accuracy: 0.6592
Epoch 29/60
804/804 [==============================] - 3s 4ms/step - loss: 0.8506 - accuracy: 0.6579
Epoch 30/60
804/804 [==============================] - 3s 4ms/step - loss: 0.8507 - accuracy: 0.6601
Epoch 31/60
804/804 [==============================] - 4s 5ms/step - loss: 0.8510 - accuracy: 0.6601
Epoch 32/60
804/804 [==============================] - 4s 5ms/step - loss: 0.8505 - accuracy: 0.6586
Epoch 33/60
425/804 [==============>...............] - ETA: 1s - loss: 0.8545 - accuracy: 0.6551

KeyboardInterrupt:

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [91]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=1)
# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 [==============================] - 1s 3ms/step - loss: 0.5532 - accuracy: 0.7296
Loss: 0.5531627535820007, Accuracy: 0.7295626997947693

In [ ]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy =nn_A1.evaluate(X_test_pca,y_test,verbose=1)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

In [ ]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_pca,y_test,verbose=1)


# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

### Step 3: Save each of your alternative models as an HDF5 file.

In [ ]:
# Set the file path for the first alternative model
file_path = "Resources/AlphabetSoup_A1.h5"

# Export your model to a HDF5 file
nn_A1.save(file_path)

In [ ]:
# Set the file path for the second alternative model
file_path = "Resources/AlphabetSoup_A2.h5"

# Export your model to a HDF5 file
nn_A2.save(file_path)